language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
cache:
  directories:
    - node_modules
env:
  matrix:
    - DB=sqlite3 NODE_ENV=travis-sqlite3
    - DB=mysql NODE_ENV=travis-mysql
    - DB=pg NODE_ENV=travis-pg

before_script:
  - if [ $DB == "mysql" ]; then mysql -e 'create database brute_knex_mysql'; fi
  - if [ $DB == "pg" ]; then psql -c 'create database brute_knex_pg;' -U postgres; fi

services:
  - mysql
  - postgresql

addons:
  postgresql: "9.6"
